# Generated by Django 3.0.3 on 2020-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200216_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
